#  ________  __                  _______   __    __       ______     __                         
# |        \|  \                |       \ |  \  |  \     /      \   |  \                        
#  \$$$$$$$$| $$____    ______  | $$$$$$$\ \$$ _| $$_   |  $$$$$$\ _| $$_     ______    ______  
#    | $$   | $$    \  /      \ | $$__/ $$|  \|   $$ \  | $$___\$$|   $$ \   |      \  /      \ 
#    | $$   | $$$$$$$\|  $$$$$$\| $$    $$| $$ \$$$$$$   \$$    \  \$$$$$$    \$$$$$$\|  $$$$$$\
#    | $$   | $$  | $$| $$    $$| $$$$$$$ | $$  | $$ __  _\$$$$$$\  | $$ __  /      $$| $$   \$$
#    | $$   | $$  | $$| $$$$$$$$| $$      | $$  | $$|  \|  \__| $$  | $$|  \|  $$$$$$$| $$      
#    | $$   | $$  | $$ \$$     \| $$      | $$   \$$  $$ \$$    $$   \$$  $$ \$$    $$| $$      
#     \$$    \$$   \$$  \$$$$$$$ \$$       \$$    \$$$$   \$$$$$$     \$$$$   \$$$$$$$ \$$      
#    本插件由 YeyingXingchen, KleeLoveLife, Rabbit0w0, Araykal 开发
#    YeyingXingchen 负责ThePitStar插件的主要开发和维护，其它几位为原ThePitUltimate插件的开发
#    配置文件中用不到的配置可以删除或注释
#    项目开源地址：https://github.com/yeying-xingchen/ThePitStar
#    Fork from https://github.com/ShanguanLinG/ThePitUltimate-Public

## 数据库
service:
  mongodb:
    ip: 127.0.0.1 # 数据库IP
    port: 27017 # 数据库端口
    database: thePit # 数据库名称
    user: admin # 数据库用户名
    password: admin # 数据库密码
# Debug选项
debug:
  debugServer: false
  public: true
  performanceLogging: false # 是否开启性能日志记录
  infinityNpcLoc: # NPC位置
    ==: org.bukkit.Location
    world: world
    x: -9.117847274619841
    y: 101.0
    z: -6.306275814520202
    pitch: 38.875862
    yaw: -273.7115

# 数据保存选项
save:
  #自动保存间隔（tick），20tick=1min
  autoSaveInterval: 12000

# 菜单选项
menu:
  # 精通确认菜单显示时间（tick），默认5tick
  confirmMenuDuration: 5

#宵禁设置
curfew:
  #启用
  enable: false
  #几点开始
  start: 0
  #几点结束
  end: 7

server-name: "&e天坑乱斗" # 服务器名称
bot-name: "&cBot" # 刷人头Bot名称
#阵营活动开始时间戳
#https://tool.lu/timestamp/
#时间戳网址↑
genesis-start-date: 1675339795842

# 计分板选项
scoreboard:
  viewSwitchMapCooldownPre30s: false # 是否开启30s内换图播报

currentMapId: 0
#设置 -1 为关闭 轮换, 详细id见当前目录下的 worlds/world.yml
duration: -1